### ISSUE TITLE
Desmatricular aluno não está funcionando

### ISSUE THREAD

**Issue by nicolasfischer1** [nicolasfischer1/projeto-Sistema-Cursos-PRP#1]
A opção 14 do menu, que funciona através da função de desmatricular aluno, presente na biblioteca "Manipulacao_Aluno.h" não está realizado o que é solicitado.
@BrunoTrojahnBolzan, como  função é de sua autoria, por favor, verifique o que está ocorrendo. Qualquer coisa nos acione!

**Comment by BrunoTrojahnBolzan** [comment]
O problema foi resolvido.
