### ISSUE TITLE
Lista de espera desatualizada

### ISSUE THREAD

**Issue by nicolasfischer1** [nicolasfischer1/projeto-Sistema-Cursos-PRP#2]
É necessário que seja criada uma função que atualize os alunos da lista de espera e as turmas. Ela será utilizada quando cadastrar uma nova turma e tiver algum aluno com código auxiliar (aluno.aux) igual ao código da turma e também, quando a turma (cheia) for esvaziada!
@patrickpriebe, é de sua autoria funções principais de manipulação dos alunos, por favor, desenvolva a função. Qualquer coisa nos acione!

**Comment by patrickpriebe** [comment]
Função criada! @nicolasfischer1
