### ISSUE TITLE
A função que edita dados do aluno gera ambiguidades!

### ISSUE THREAD

**Issue by nicolasfischer1** [nicolasfischer1/projeto-Sistema-Cursos-PRP#4]
Toda vez que é necessário trocar a turma do aluno, opção disponível na função de editar aluno, os dados no arquivo "Turmas.bin" não são atualizados, como por exemplo: o nº de alunos na turma.

**Comment by BrunoTrojahnBolzan** [comment]
O problema foi resolvido no último commit ao arquivo "Manipulacao_Alunos.h".
