### ISSUE TITLE
A função de desmatricular o aluno não está decrementando na quantidade de alunos da turma!

### ISSUE THREAD

**Issue by patrickpriebe** [nicolasfischer1/projeto-Sistema-Cursos-PRP#5]
@BrunoTrojahnBolzan verifique a função novamente para corrigir este problema. Eu e o @nicolasfischer1 realizamos um laboratório de testes e constatamos este problema!

**Comment by BrunoTrojahnBolzan** [comment]
A função desmatricular agora decrementa a quantidade de alunos no arquivo de turmas.
